/* Invoice readability: preserve bound nodes and values; split pricing as a complete binding range. */
(() => {
  const PREFIX = 'data-st-invoice-';
  const NUMBER = /^(amount|total|subtotal|balance|quantity|qty|unit\s+(price|cost)|total\s+(price|cost|taxes)|sold\s+hours|split|%|payroll adjustments)$/i;
  const MONEY_BINDING = /formatMoney\s*\(|\b\w*PercentOfSale\b/;

  window.__ST_DEUGLIFY__?.register({
    id: 'invoice-readability',
    name: 'Invoice enhancements',
    description: 'Readable invoice details, pricing, tables, actions, and empty states.',
    matches: url => /^#\/(?:EditInvoice|Invoice)\/\d+\/?(?:\?.*)?$/i.test(url.hash) && !/[?&]print=true\b/i.test(url.search + url.hash) && !/\/(?:app\/api\/.*\/print|Invoice\/Print|Estimate\/Print)\//i.test(url.pathname || ''),
    findRoot: () => document.querySelector('.invoice-job-view'),
    mount(root) {
      // Recover a cloned, already-enhanced subtree before mounting it again.
      for (const table of root.querySelectorAll('table[data-st-invoice-pricing]')) {
        const original = table.previousElementSibling;
        if (original?.tagName === 'TABLE') original.tBodies[0].append(...table.tBodies[0].childNodes);
        table.remove();
      }
      root.setAttribute(`${PREFIX}ui`, '');
      const disposeHeader = window.__ST_DEUGLIFY_INVOICE_HEADER__?.(root);
      let timer;
      let disposed = false;
      const accessible = new Map();
      const pricing = new Map();
      let printing = false;
      function splitPricing() {
        if (printing) return;
        for (const original of root.querySelectorAll('.invoice-details-view > table:not([data-st-invoice-pricing])')) {
          if (pricing.has(original)) continue;
          const body = original.tBodies[0];
          if (!body) continue;
          const summary = [...body.rows].find(row => [...row.cells].some(c => c.classList.contains('caption') && /^Invoice Summary/.test(c.textContent.trim())));
          if (!summary || !summary.nextSibling) continue;
          // Split only outside Knockout virtual blocks. Move the entire remaining
          // sibling range, including if/foreach comments, preserving node identity.
          let depth = 0;
          for (const node of body.childNodes) {
            if (node.nodeType === 8) {
              if (/^\s*ko\s/.test(node.textContent)) depth++;
              if (/^\s*\/ko/.test(node.textContent)) depth--;
            }
            if (node === summary) break;
          }
          if (depth !== 0) continue;
          const table = document.createElement('table');
          table.setAttribute(`${PREFIX}pricing`, '');
          const caption = table.createCaption(); caption.textContent = 'Pricing details';
          const target = table.createTBody();
          while (summary.nextSibling) target.append(summary.nextSibling);
          original.after(table);
          original.setAttribute(`${PREFIX}descriptions`, '');
          pricing.set(original, table);
        }
      }
      function restorePricing() {
        for (const [original, table] of pricing) {
          original.tBodies[0].append(...table.tBodies[0].childNodes);
          original.removeAttribute(`${PREFIX}descriptions`);
          table.remove();
        }
        pricing.clear();
      }
      const beforePrint = () => { printing = true; restorePricing(); };
      const afterPrint = () => { printing = false; schedule(); };
      window.addEventListener('beforeprint', beforePrint);
      window.addEventListener('afterprint', afterPrint);
      const observed = new Set();
      const resize = new ResizeObserver(schedule);

      function remember(el, name, value) {
        let entries = accessible.get(el);
        if (!entries) accessible.set(el, entries = new Map());
        if (!entries.has(name)) entries.set(name, { before: el.getAttribute(name), ours: value });
        el.setAttribute(name, value);
      }

      function restore(el) {
        const entries = accessible.get(el);
        if (!entries) return;
        for (const [name, { before, ours }] of entries) {
          // Do not overwrite a later change made by ServiceTitan.
          if (el.getAttribute(name) !== ours) continue;
          if (before === null) el.removeAttribute(name); else el.setAttribute(name, before);
        }
        accessible.delete(el);
      }

      function polishPresentation() {
        for (const heading of root.querySelectorAll('h3')) {
          if (!/^(Lead Generated By|Sold By)/.test(heading.textContent.trim())) continue;
          heading.setAttribute(`${PREFIX}attribution`, '');
          if (!heading.hasAttribute('role')) remember(heading, 'role', 'group');
          const value = heading.querySelector('span[data-bind]');
          if (!value) continue;
          const empty = /^\s*(\[None\]|None)?\s*$/.test(value.textContent);
          heading.toggleAttribute(`${PREFIX}empty`, empty);
          value.toggleAttribute(`${PREFIX}empty-value`, empty);
          let placeholder = heading.querySelector('.st-invoice-empty-attribution');
          if (empty && !placeholder) {
            placeholder = document.createElement('span');
            placeholder.className = 'st-invoice-empty-attribution';
            placeholder.setAttribute(`${PREFIX}generated`, '');
            placeholder.setAttribute('aria-hidden', 'true');
            placeholder.textContent = 'Not assigned'; heading.append(placeholder);
          } else if (!empty) placeholder?.remove();
        }
        for (const cell of root.querySelectorAll('[data-st-invoice-descriptions] td[data-bind]')) {
          cell.toggleAttribute(`${PREFIX}empty-summary`, /formattedText:.*SafeSummary/.test(cell.getAttribute('data-bind')) && /^Unspecified\s*\.{0,3}$/.test(cell.textContent.trim()));
        }
        for (const panel of root.querySelectorAll('[data-bind*="InvoiceMoveItemsButton"]')) {
          panel.setAttribute(`${PREFIX}bulk-actions`, '');
          let hint = panel.querySelector('.st-invoice-selection-hint');
          if (!hint) {
            hint = document.createElement('span'); hint.className = 'st-invoice-selection-hint';
            hint.setAttribute(`${PREFIX}generated`, '');
            hint.textContent = 'Select line items to move'; panel.append(hint);
          }
          const hideHint = !panel.querySelector('button:disabled') || !!root.querySelector('.list-view tbody input[type="checkbox"]:checked');
          if (hint.hidden !== hideHint) hint.hidden = hideHint;
        }
        for (const link of root.querySelectorAll('.list-view table tbody a')) {
          const action = link.querySelector('.icon-pencil') ? 'Edit item' : link.querySelector('.icon-remove') ? 'Remove item' : '';
          if (action) {
            if (!link.hasAttribute('aria-label') && !link.hasAttribute('title')) remember(link, 'aria-label', action);
            if (!link.hasAttribute('href')) {
              link.setAttribute(`${PREFIX}action`, '');
              if (!link.hasAttribute('role')) remember(link, 'role', 'button');
              if (!link.hasAttribute('tabindex')) remember(link, 'tabindex', '0');
            }
          }
        }
      }

      function separateMaterialTotals() {
        // ServiceTitan repeats material costs in the technician footer. Suppress
        // only an exact duplicate already visible in Materials, without moving
        // bound nodes out of their Knockout context or calculating any amounts.
        const visible = el => el.getClientRects().length > 0 && getComputedStyle(el).visibility === 'visible';
        const values = row => [...row.querySelectorAll('[data-bind]')]
          .filter(cell => MONEY_BINDING.test(cell.getAttribute('data-bind')))
          .map(cell => cell.textContent.trim());
        const materialRows = [...root.querySelectorAll('.materials-view tfoot tr')].filter(visible);
        for (const row of root.querySelectorAll('.invoice-technicians-view tfoot tr')) {
          const isMaterialTotal = [...row.cells].some(cell => /^Total Material Costs:?$/i.test(cell.textContent.trim()));
          const amounts = values(row);
          const duplicate = isMaterialTotal && amounts.length > 0 && amounts.every(Boolean) && materialRows.some(material => {
            const other = values(material);
            return other.length === amounts.length && amounts.every((value, index) => value === other[index]);
          });
          row.toggleAttribute(`${PREFIX}duplicate-material-total`, duplicate);
        }
      }

      function annotate() {
        timer = undefined;
        if (disposed) return;
        splitPricing();
        polishPresentation();
        separateMaterialTotals();
        for (const el of observed) {
          if (!root.contains(el)) { resize.unobserve(el); observed.delete(el); restore(el); }
        }
        for (const el of accessible.keys()) if (!root.contains(el)) restore(el);
        root.querySelectorAll(`[${PREFIX}number], [${PREFIX}column]`).forEach(el => {
          el.removeAttribute(`${PREFIX}number`);
          el.removeAttribute(`${PREFIX}column`);
        });

        for (const table of root.querySelectorAll('.list-view table.table-condensed')) {
          table.setAttribute(`${PREFIX}table`, '');
          const header = table.tHead?.rows[table.tHead.rows.length - 1];
          const numeric = [];
          const kinds = [];
          if (header) {
            let column = 0;
            for (const cell of header.cells) {
              const label = cell.textContent.trim().replace(/\s+/g, ' ');
              const isNumeric = NUMBER.test(label);
              const kind = /^(description|summary)$/i.test(label) ? 'description'
                : /^(name|vendor|technician|business unit)$/i.test(label) ? 'name'
                : /^(code|#|legacy id)$/i.test(label) ? 'code'
                : !label && cell.querySelector('input[type="checkbox"]') ? 'selection'
                : !label ? 'actions' : '';
              for (let span = 0; span < cell.colSpan; span++) {
                numeric[column] = isNumeric;
                kinds[column++] = kind;
              }
            }
          }
          for (const row of table.rows) {
            let column = 0;
            for (const cell of row.cells) {
              // Never infer a multi-column subtotal label as an amount.
              const binding = cell.getAttribute('data-bind') || '';
              const totalLabel = /^(?:Total(?: Material Costs| Cost)?|Subtotal|Markup|Charge Total):?$/i.test(cell.textContent.trim());
              cell.toggleAttribute(`${PREFIX}total-label`, totalLabel);
              if (!totalLabel && ((cell.colSpan === 1 && numeric[column]) || MONEY_BINDING.test(binding))) {
                cell.setAttribute(`${PREFIX}number`, '');
              }
              if (cell.colSpan === 1 && kinds[column]) cell.setAttribute(`${PREFIX}column`, kinds[column]);
              column += cell.colSpan;
            }
          }
          // Existing sections wrap the tables; no reparenting of bound DOM.
          const section = table.parentElement;
          if (section?.tagName !== 'SECTION') continue;
          section.setAttribute(`${PREFIX}scroll`, '');
          if (!observed.has(section)) { observed.add(section); resize.observe(section); }
          if (section.clientWidth > 0 && section.scrollWidth > section.clientWidth + 1) {
            if (!section.hasAttribute('tabindex')) remember(section, 'tabindex', '0');
            if (!section.hasAttribute('role')) remember(section, 'role', 'region');
            if (!section.hasAttribute('aria-label') && !section.hasAttribute('aria-labelledby')) {
              const heading = section.closest('.list-view')?.querySelector('h2');
              remember(section, 'aria-label', `${heading?.textContent.trim() || 'Invoice'} table; scroll for more columns`);
            }
          } else restore(section);
        }
        // Emphasis follows field meaning, never whichever row happens to be last.
        for (const row of root.querySelectorAll('table[data-st-invoice-pricing] > tbody > tr')) {
          for (const cell of row.cells) cell.removeAttribute(`${PREFIX}total`);
          for (const cell of row.cells) {
            if (cell.classList.contains('caption') && /^(Total|Balance)$/.test(cell.textContent.trim())) {
              cell.setAttribute(`${PREFIX}total`, '');
              cell.nextElementSibling?.setAttribute(`${PREFIX}total`, '');
            }
          }
        }
        // Hide only empty layout spacers; keep every bound value and control.
        for (const row of root.querySelectorAll('.invoice-details-view > table > tbody > tr')) {
          for (const cell of row.cells) {
            const spacer = !cell.classList.contains('caption') &&
              !cell.textContent.trim() && !cell.children.length &&
              !cell.hasAttribute('data-bind') && !cell.previousElementSibling?.classList.contains('caption');
            cell.toggleAttribute(`${PREFIX}spacer`, spacer);
          }
        }
        for (const cell of root.querySelectorAll('.invoice-details-view td[data-bind]')) {
          if (MONEY_BINDING.test(cell.getAttribute('data-bind'))) cell.setAttribute(`${PREFIX}number`, '');
        }
      }

      function schedule() {
        if (!disposed && timer === undefined) timer = setTimeout(annotate, 60);
      }
      const observer = new MutationObserver(records => {
        if (records.some(record => record.attributeName !== 'style' ||
          record.target.closest('.materials-view') || record.target.querySelector('.materials-view'))) schedule();
      });
      observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ['disabled', 'hidden', 'style'] });
      root.addEventListener('change', schedule);
      const actionKey = event => {
        const action = event.target.closest?.('[data-st-invoice-action]');
        if (action && ['Enter', ' '].includes(event.key) && !action.matches('.disabled,[aria-disabled="true"]')) {
          event.preventDefault(); action.click();
        }
      };
      root.addEventListener('keydown', actionKey);
      annotate();
      return () => {
        disposed = true;
        clearTimeout(timer);
        observer.disconnect();
        root.removeEventListener('change', schedule);
        root.removeEventListener('keydown', actionKey);
        root.querySelectorAll('.st-invoice-empty-attribution,.st-invoice-selection-hint').forEach(el => el.remove());
        resize.disconnect();
        window.removeEventListener('beforeprint', beforePrint);
        window.removeEventListener('afterprint', afterPrint);
        restorePricing();
        disposeHeader?.();
        for (const el of accessible.keys()) restore(el);
        for (const el of [root, ...root.querySelectorAll('*')]) {
          for (const attr of [...el.attributes]) if (attr.name.startsWith(PREFIX)) el.removeAttribute(attr.name);
        }
      };
    }
  });
})();
