document.querySelector('#tests').onclick = async () => {
  const output = document.querySelector('#results'); output.textContent = '';
  const results = [];
  const check = (name, ok) => { results.push(`${ok ? 'PASS' : 'FAIL'} ${name}`); output.textContent = results.join('\n'); };
  const wait = () => new Promise(resolve => setTimeout(resolve, 180));
  const form = document.querySelector('form'), native = form.elements.NewEmailAddress;
  const { model, sent } = window.emailFixture;
  const search = () => form.querySelector('.st-email-search');
  const dropdown = () => form.querySelector('.st-email-dropdown');
  const enter = value => { search().value = value; search().dispatchEvent(new Event('input', { bubbles: true })); };
  const key = value => search().dispatchEvent(new KeyboardEvent('keydown', { key: value, bubbles: true, cancelable: true }));
  const choose = () => dropdown().querySelector('[role="option"]').click();
  const body = form.elements.Body.value;
  const nativeControls = [...form.querySelectorAll('input,select,textarea,button')].filter(el => !el.closest('[data-st-email-generated]'));
  check('Picker mounts without selecting anyone', !!search() && model.SelectedEmails().length === 0);
  check('Native checkboxes and legacy input are hidden', !form.querySelector('input[value="customer@example.com"]').getClientRects().length && !native.getClientRects().length);
  form.requestSubmit();
  check('Empty recipient selection blocks Send', sent.length === 0);
  search().focus();
  check('Focus opens dropdown with saved customer address', !dropdown().hidden && dropdown().textContent.includes('customer@example.com'));
  const group = form.querySelector('[data-st-email-section="to"]');
  enter('');
  const beforeHeight = group.getBoundingClientRect().height;
  choose(); await wait();
  check('Clicking saved address creates a selected pill and checks native control', model.SelectedEmails()[0] === 'customer@example.com' && !!form.querySelector('[aria-label="Remove customer@example.com"]') && form.querySelector('input[value="customer@example.com"]').checked);
  check('First recipient does not move the following form sections', Math.abs(beforeHeight - group.getBoundingClientRect().height) < 1);
  check('Dropdown closes after selection', dropdown().hidden);
  search().click(); enter('missing');
  check('Filtering hides nonmatching contacts', !dropdown().querySelector('[role="option"]'));
  enter('one@example.com');
  check('Valid new email becomes a dropdown option', dropdown().textContent.includes('one@example.com') && dropdown().textContent.includes('Add email'));
  choose(); await wait();
  check('Clicking new email adds native selection and clears search', model.SelectedEmails().includes('one@example.com') && !search().value);
  enter('two@example.com; three@example.com'); key('Enter'); await wait();
  check('Enter adds multiple new addresses without submitting', model.SelectedEmails().includes('two@example.com') && model.SelectedEmails().includes('three@example.com') && sent.length === 0);
  enter('ONE@example.com'); key('Enter'); await wait();
  check('Duplicates are ignored case-insensitively', model.SelectedEmails().length === 4);
  form.querySelector('[aria-label="Remove one@example.com"]').click(); await wait();
  check('Removing pill updates native selection', !model.SelectedEmails().includes('one@example.com') && !form.querySelector('input[value="one@example.com"]').checked);
  enter('one@'); key('ArrowDown');
  check('Arrow keys expose an active dropdown option', !!search().getAttribute('aria-activedescendant'));
  key('Enter'); await wait();
  check('Keyboard selection restores existing address', model.SelectedEmails().includes('one@example.com'));
  search().click(); key('Escape');
  check('Escape closes dropdown', dropdown().hidden && search().getAttribute('aria-expanded') === 'false');
  search().click(); document.body.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
  check('Outside click closes dropdown', dropdown().hidden);
  enter('invalid'); key('Enter'); await wait();
  check('Invalid address is retained with error and no selection change', search().value === 'invalid' && model.SelectedEmails().length === 4 && !!form.querySelector('.st-email-status[data-error]'));
  form.requestSubmit();
  check('Unconfirmed search text blocks Send', sent.length === 0);
  enter(''); form.requestSubmit();
  check('Confirmed recipients flow into original submit', sent.length === 1 && sent[0].selected.length === 4 && sent[0].body === body);
  check('Helper and contact-saving toggle are absent', !form.querySelector('.st-email-help, .st-email-native-toggle'));
  check('Successful selection leaves no status message or empty feedback space', !form.querySelector('.st-email-status').textContent && !form.querySelector('.st-email-status').getClientRects().length);
  native.value = 'save@example.com'; native.dispatchEvent(new Event('input', { bubbles: true }));
  form.elements.SaveCustomerEmailAddress.click(); model.SelectedContactId(123);
  enter('other@example.com'); key('Enter'); await wait();
  check('Picker preserves native draft and contact association', model.NewEmailAddress() === 'save@example.com' && model.SelectedContactId() === 123 && model.SaveCustomerEmailAddress() && model.SelectedEmails().includes('other@example.com'));
  form.requestSubmit();
  check('Contact-saving UI stays hidden even with a native draft', !form.querySelector('.save-email-address').getClientRects().length);
  check('Native pending address is still submitted', sent.at(-1).draft === 'save@example.com');
  native.value = ''; native.dispatchEvent(new Event('input', { bubbles: true }));
  form.elements.SaveCustomerEmailAddress.click(); model.SelectedContactId(null);
  document.documentElement.removeAttribute('data-st-beautify'); await wait();
  check('Disable restores native controls and removes picker', !search() && !!native.getClientRects().length && !!form.querySelector('input[value="two@example.com"]').getClientRects().length);
  form.querySelector('input[value="two@example.com"]').click();
  check('Added native choices still work with Beautify off', !model.SelectedEmails().includes('two@example.com'));
  document.documentElement.setAttribute('data-st-beautify', 'on'); await wait();
  check('Reenable reflects selected recipients', form.querySelectorAll('.st-email-chip').length === model.SelectedEmails().length);
  const binding = window.ko; window.ko = undefined;
  form.dispatchEvent(new Event('change', { bubbles: true })); await wait();
  check('Bridge failure restores native input and checkboxes', search().disabled && !!native.getClientRects().length && !!form.querySelector('input[value="customer@example.com"]').getClientRects().length);
  window.ko = binding; form.dispatchEvent(new Event('change', { bubbles: true })); await wait();
  check('Bridge recovery restores picker', !search().disabled && form.hasAttribute('data-st-email-picker-ready'));
  check('Bound controls and message are preserved', nativeControls.every(el => form.contains(el)) && form.elements.Body.value === body);
  history.pushState(null, '', '#/EditInvoice/10001'); await wait();
  form.dispatchEvent(new Event('change', { bubbles: true })); await wait();
  check('Outgoing form stays styled until removed', form.hasAttribute('data-st-email-ui') && form.hasAttribute('data-st-email-picker-ready'));
  const parent = form.parentNode, sibling = form.nextSibling;
  form.remove(); await wait();
  check('Removing outgoing form cleans up', !form.hasAttribute('data-st-email-ui'));
  parent.insertBefore(form, sibling); await wait();
  check('Unrelated route cannot mount email UI', !form.hasAttribute('data-st-email-ui'));
  history.pushState(null, '', '#/Invoice/Email/10001'); await wait();
  check('Route return creates one picker', form.querySelectorAll('.st-email-search').length === 1);
  window.dispatchEvent(new Event('beforeprint'));
  check('Print removes email presentation', !form.hasAttribute('data-st-email-ui'));
  window.dispatchEvent(new Event('afterprint')); await wait();
  check('Print return restores picker', !!search());
  const frame = document.createElement('iframe'); frame.title = 'Narrow email fixture'; frame.style.cssText = 'width:420px;height:800px;max-width:100%;border:0';
  const loaded = new Promise(resolve => { frame.onload = resolve; }); frame.src = location.pathname; document.body.append(frame); await loaded; await wait();
  check('Narrow picker layout avoids horizontal overflow', frame.contentDocument.documentElement.scrollWidth <= frame.clientWidth + 1); frame.remove();
  for (const dark of [false, true]) {
    dark ? document.documentElement.setAttribute('data-st-dark', 'on') : document.documentElement.removeAttribute('data-st-dark');
    check(`${dark ? 'Dark' : 'Light'} picker stays usable`, !!search().getClientRects().length && !search().disabled);
  }
  document.documentElement.removeAttribute('data-st-dark');
  output.textContent += `\n${results.filter(x => x.startsWith('PASS')).length}/${results.length} checks passed`;
};
